// <auto-generated />
using System;
using DirectoryFolders.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DirectoryFolders.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230428103453_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DirectoryFolders.Models.Folder", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("FolderID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentFolderID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("FolderID");

                    b.ToTable("Folders");
                });

            modelBuilder.Entity("DirectoryFolders.Models.Folder", b =>
                {
                    b.HasOne("DirectoryFolders.Models.Folder", null)
                        .WithMany("ChildFolders")
                        .HasForeignKey("FolderID");
                });

            modelBuilder.Entity("DirectoryFolders.Models.Folder", b =>
                {
                    b.Navigation("ChildFolders");
                });
#pragma warning restore 612, 618
        }
    }
}
